version: '3'

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cardb
    networks:
      - car-network
    restart: always
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: cardb-volume
        target: /var/lib/mysql

  api:
    container_name: api
    image: sam473/lbg-car-back:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    ports:
      - 8072:8072
    restart: always
    networks:
      - car-network

  user-interface:
    image: sam473/lbg-car-front:latest
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - car-network

networks:
  car-network:
volumes:
  cardb-volume: